import csv
import pandas as pd
import matplotlib.pyplot as plt

with open ("fit_run.csv", "r") as csv_file:
    csv_reader = csv.reader(csv_file)
#Lee los archivos CSV
df_run= pd.read_csv ("fit_run.csv", sep=",")
df_gym=pd.read_csv ("fit_gym.csv", sep=",")

print(df_gym.head())
print()
print(df_run.head())
print()
print(df_gym.info())
print()
print(df_run.info())
print()
print(df_gym.describe())
print()
print(df_run.describe())
print()
# Gráfico de barras para contar tipos de ejercicios
plt.figure(figsize=(10, 6))
df_gym['ejercicio'].value_counts().plot(kind='bar', color='orange')
plt.title('Conteo de Tipos de Ejercicios de Gym')
plt.xlabel('Tipo de Ejercicio')
plt.ylabel('Cantidad')
plt.xticks(rotation=45)
plt.show()
print()
plt.figure(figsize=(10, 6))
df_run['ejercicio'].value_counts().plot(kind='bar', color='red')
plt.title('Conteo de Tipos de Ejercicios de Gym')
plt.xlabel('Tipo de Ejercicio')
plt.ylabel('Cantidad')
plt.xticks(rotation=45)
plt.show()
print()
# Visualización de la distribución de la dificultad
plt.figure(figsize=(8, 6))
plt.hist(df_gym['dificultad'], bins=10, color='skyblue', alpha=0.7)
plt.title('Distribución de la Dificultad de gym')
plt.xlabel('Nivel de Dificultad')
plt.ylabel('Frecuencia')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
print()
plt.figure(figsize=(8, 6))
plt.hist(df_run['dificultad'], bins=10, color='pink', alpha=0.7)
plt.title('Distribución de la Dificultad de run')
plt.xlabel('Nivel de Dificultad')
plt.ylabel('Frecuencia')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
print()
plt.figure(figsize=(8, 6))
plt.scatter(df_gym['dificultad'], df_gym['peso'], color='green', alpha=0.5)
plt.title('Relación entre la Dificultad y el Peso')
plt.xlabel('Dificultad')
plt.ylabel('Peso/kg')
plt.show()
print()
plt.figure(figsize=(8, 6))
plt.scatter(df_run['distancia'], df_run['tiempo'], color='green', alpha=0.5)
plt.title('Relación entre la Distancia y el Tiempo')
plt.xlabel('Distancia/km')
plt.ylabel('Tiempo/min')
plt.show()
